<?php

namespace AppBundle\Repository;


/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSortedQuery()
    {
        return $this
            ->createQueryBuilder('o')
            ->select('o')
            ->orderBy('o.createdOn','DESC');
    }
}
